version: "3"
services:
  mysql-db:
    image: mysql
    container_name: mysql_prod
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eventprojectdb
    volumes:
      - db:/var/lib/mysql

  app-maven:
    depends_on:
      - mysql-db
    image: maminizer/repo:latest
    container_name: eventproject
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-db:3306/eventprojectdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update" 
        }'
    volumes:
      - .m2:/root/.m2

  spring-app:
    image: firas1412/eventprojectfront:latest
    container_name: eventprojectangular
    restart: on-failure
    ports:
      - 4200:80
    depends_on:
      - app-maven

volumes:
  db:
  mysql-data:
